import type { Metadata } from "next";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/authOptions";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { Sarabun } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import NavbarWrapper from "@/components/NavbarWrapper"; // Use NavbarWrapper instead of Navbar

const sarabun = Sarabun({ subsets: ["thai", "latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="th">
      <body className={sarabun.className}>
        <ReduxProvider>
          <NextAuthProvider session={session}>
            <NavbarWrapper /> {/* Now uses the Client Component */}
            {children}
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
